#!/usr/bin/env python3
"""Pack sound/web/*.mp3 into two files beside the page, and put their index in the page between
the SND markers. The page stays small: the packs are fetched only after the first tap, the first
moment a browser lets a page make a sound at all.

  sound-fx.bin     everything a phone can play: buttons, cards, trades, the police on your block,
                   the skills and talents, the fight, the taunt when you are robbed
  sound-table.bin  what only the table screen plays (and a phone that asks to hear the whole
                   table): the announcer, the dice machine, the city at night, the start sting

Each pack is the MP3s end to end; the index says where each clip starts, how long it is, and its
length in seconds. Each pack's URL carries a hash of its contents, so a new version is never
served from an old cache.
Usage: python3 sound/embed.py index.html    (writes the packs next to it)"""
import hashlib, json, os, sys
here = os.path.dirname(os.path.abspath(__file__)); web = os.path.join(here, "web")
meta = json.load(open(os.path.join(web, "meta.json")))
PARTS = {"squelch_in", "squelch_out"}          # only exist to be built into other clips
# heard only from the table (sndHearsTable): the announcer, save the taunt a robbed phone hears too
TABLE = {"amb_city", "start", "turn", "join", "leave", "tension", "reel_spin", "reel_stop", "payout", "seven",
         "crash_skid", "crash_hit", "crash_boom", "crash_bump", "horn_1", "horn_2"}     # the traffic crashing (drive)
def pack_of(n):
    if n.startswith("v_") and not n.startswith("v_taunt_"): return "table"
    return "table" if n in TABLE else "fx"

page = sys.argv[1]; out_dir = os.path.dirname(os.path.abspath(page))
names = [n for n in sorted(meta) if n not in PARTS and os.path.exists(os.path.join(web, n + ".mp3"))]
blobs, clips, packs = {"fx": bytearray(), "table": bytearray()}, {}, {}
for n in names:
    p = pack_of(n); data = open(os.path.join(web, n + ".mp3"), "rb").read()
    clips[n] = [p, len(blobs[p]), len(data), meta[n]]
    blobs[p] += data
for p, b in blobs.items():
    fn = "sound-%s.bin" % p
    open(os.path.join(out_dir, fn), "wb").write(b)
    packs[p] = {"url": fn, "v": hashlib.sha1(b).hexdigest()[:10], "size": len(b)}
index = json.dumps({"packs": packs, "clips": clips}, separators=(",", ":"))
block = ('<!-- SND:BEGIN (generated by sound/embed.py, do not edit by hand) -->\n'
         '<script type="application/json" id="snd-index">%s</script>\n<!-- SND:END -->' % index)
s = open(page, encoding="utf-8").read()
if "<!-- SND:BEGIN" in s:
    a, b = s.index("<!-- SND:BEGIN"), s.index("<!-- SND:END -->") + len("<!-- SND:END -->")
else:
    a = b = s.index("<!-- ART:END -->") + len("<!-- ART:END -->"); block = "\n" + block
s = s[:a] + block + s[b:]
open(page, "w", encoding="utf-8").write(s)
print("%d clips: sound-fx.bin %d KB (%d clips), sound-table.bin %d KB (%d clips); index %d KB; page %d KB" % (
    len(clips), packs["fx"]["size"] // 1024, sum(1 for c in clips.values() if c[0] == "fx"),
    packs["table"]["size"] // 1024, sum(1 for c in clips.values() if c[0] == "table"), len(index) // 1024, len(s.encode()) // 1024))
